Bootstrap: docker
From: ubuntu:latest

%runscript

     cd /data
     exec python3 -m http.server 9999

%post
     apt-get update
     export TZ=Asia/Kolkata
     ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
     apt-get -y install git make python3 wget build-essential cmake curl
     git clone https://github.com/spack/spack.git --depth=1 /opt/spack
     . /opt/spack/share/spack/setup-env.sh
     spack compiler add
     spack install cuda
     spack install nvhpc
     spack load nvhpc
     spack compiler add
     spack install hdf5 +cxx +fortran +hl -mpi %nvhpc
     mkdir /data
     cd /data
     git clone https://github.com/Nischay-Pro/mfcfd.git --branch=hdf5-sec-order --depth=1 fortran
     cd fortran/install
     spack unload
     spack load cuda
     spack load nvhpc
     spack load hdf5
     CUDA_CUDART_LIBRARY=$(spack location -i cuda)/targets/x86_64-linux/lib/libcudart.so python3 install.py --mfcfd cuda